### ISSUE TITLE
[Q4wHR0BS] test a/b

### ISSUE THREAD

**Issue by issuemanager** [issuemanager/demo-A#7]

**Comment by psturm** [comment]
[trello]
test :smirk:

**Comment by issuemanager** [comment]
test message forward

---

<a target=_blank href="https://trello.com/c/Q4wHR0BS/5-test-a-b"><img src="http://img.shields.io/badge/trello-test a/b-blue.svg" /></a> <a target=_blank href="https://github.com/issuemanager/demo-A/issues/8"><img src="http://img.shields.io/badge/demo-A-8-blue.svg" /></a> <a target=_blank href="https://github.com/issuemanager/demo-A/issues/7"><img src="http://img.shields.io/badge/demo-A-7-blue.svg" /></a>

**Comment by issuemanager** [comment]
fin

---

<a target=_blank href="https://trello.com/c/Q4wHR0BS/5-test-a-b"><img src="http://img.shields.io/badge/trello-test a/b-blue.svg" /></a> <a target=_blank href="https://github.com/issuemanager/demo-A/issues/8"><img src="http://img.shields.io/badge/demo-A-8-blue.svg" /></a> <a target=_blank href="https://github.com/issuemanager/demo-A/issues/7"><img src="http://img.shields.io/badge/demo-A-7-blue.svg" /></a>
